### ISSUE TITLE
volume mounting to more than one container

### ISSUE THREAD

**Issue by rmartinez3** [contiv/volplugin#206]
I made a volume with volplugin. Saw that i was able to mount with it in different hosts while having volplugin running. However, if i tried mounting the volume with more than one container, it either tells me that there is a lock or sometimes it seems to mess things up and im not able to mount to the volume anymore.

**Comment by erikh** [comment]
Yes. This is partially a feature and partially a bug in docker.

Unfortunately due to how ceph works with the linux fs cache (I think, at least), you can't multi-host mount volumes safely. So we implemented a locking mechanism to disallow multi-host mounts.

The second set of issues you are seeing (the volume disappearing) is likely https://github.com/contiv/volplugin/issues/167 which is going to be fixed in docker 1.11 (it will take a day or two to implement the changes on our side). The only real solution right now is to fully clear the container before attempting to reference it again on the same host, otherwise a double umount will happen when the container fails to run the second one.

**Comment by rmartinez3** [comment]
got it . thanks for the quick response

**Comment by erikh** [comment]
note that if you trigger the double unmount the only real fix is to restart docker.

thanks again for the report!
