### ISSUE TITLE
volplugin question.

### ISSUE THREAD

**Issue by angry-tony** [contiv/volplugin#262]
I'm a new to volplugin.
how to install volplugin on pre existing centos 7.2 instances, such as a set of bare-metal machines with Centos 7.2 installed?
is there any documentation or instruction ??

**Comment by erikh** [comment]
Hi Tony,

Sure. What we have is our github.com/contiv/ansible repository. If you're not familiar with ansible, you'll want to learn it @ ansible.com. If you are, check out our [Vagrantfile](https://github.com/contiv/volplugin/blob/master/Vagrantfile) for the vars you need to provide to provision both netplugin and volplugin. 

/cc @shaleman since he also has a netplugin ticket here: https://github.com/contiv/netplugin/issues/370

**Comment by erikh** [comment]
We also have our cluster product @ https://github.com/contiv/cluster and that may help you with your provisioning needs. /cc @mapuri

**Comment by angry-tony** [comment]
wow.. it's great.. 
thank you for your info.. I will try it.. thanks.

**Comment by erikh** [comment]
Hey Tony, since I seemed to answer your questions, I'm going to close this. Please feel free to open a new ticket if you run into specific issues.

Thanks!
