### ISSUE TITLE
Option to lock mounts on the same host

### ISSUE THREAD

**Issue by CBR09** [contiv/volplugin#295]
Hi @erikh and everyone,
When I create a container with rbd image, I want to lock rbd image to prevent the other container use it. Mean don't allow two containers use same rbd image. 
I've tried use both unlocked: false and unlocked: true, they didn't work, they allow two containers on same host use same rbd image. So, how can I do that ?
Thanks

**Comment by CBR09** [comment]
> OK. Thanks, we will do our best to accommodate the needs here, but I ran
> into some technical barriers implementing local locks. Namely, the
> existence checks I was using were more like schrödinger's cat than a
> light switch.
> 
> In reality, the technical barrier is probably me here. Some ideas we can
> try in the near future:
> 
> Perhaps once Docker 1.12 is out, the volumes API will have a new unique
> identifier we can key on, this could make the locking schemes much
> richer. I need to investigate a little more. If you're willing to wait
> for that, of course. :)
> 
> We could also delegate this to the storage driver, which could use
> rbd-lock to acquire its ceph volumes. We didn't have much success with
> RBD locking before but this would be an excellent use case for it. I see
> this as potentially necessary for a number of drivers we may write soon
> as well.
Hi @erikh 
I suppose you answer to me at this issue :D.
Thanks you for all you have done, I will keep watching volplugin in future.
I think delegate lock mechanism to storage driver would be an great idea. With ceph, you can use rbd add lock and volplugin will check rbd lock before mount, look like https://github.com/porcupie/rbd-docker-plugin have done.
Thanks

**Comment by erikh** [comment]
Familiar with the project; we initially implemented locking this way. At 
high volumes (many locks acquired for the same volume over a short 
period of time) RBD locking seemed to break down a lot, so I didn't feel 
comfortable relying on it. Also, there is no NFS story here and we want 
to start implementing lots of backends aside from NFS and Ceph.

That said, there seems to be a good case for them now -- on the same 
host -- and if I can ensure they're reliable that will be an easy patch. 
NFS yields EBUSY so we get that lock kinda-sorta for free.

Let me tinker for a bit and get back to you, we're also still testing on 
ceph 9 so there's that we should fully vet 10 too. The problem with 
making all the locking happen in the storage driver is that we can't 
build as reliable an abstraction, because there are more code paths to 
take depending on the underlying locking mechanism used.

Anyhow, I'm going to lock this now so we stop emailing everyone on a 
closed issue. Please open a new issue if you'd like to discuss changes 
you'd like to see. Feel free to email me as well.

Thanks!

**Comment by erikh** [comment]
whoops! I didn't realize this was a new issue! Been doing this all from email so far LOL.

Let's leave this open to discuss it.

/cc @mapuri @jainvipin @dseevr @unclejack

**Comment by CBR09** [comment]
I understand what you said about implement locking at storage driver, more storage drivers more code paths.
I've tried a few plugin with ceph like: rexray (need cinder), rbd-docker-plugin and volplugin, and between those things, I saw volplugin's policy feature is amazing, but I realized volplugin missing locking mechanism. that's mean I want volume (rbd image) was used by a container, no one can use it again. it's safe.
I think the way to implement, maybe save volume has been lock in etcd, and when mount operation happen, check in etcd if volume has been lock, and stop mount. just thought, I'm not good at that :)

Thanks

**Comment by erikh** [comment]
It does that across hosts. I'm working on fixing this now; I will get 
back to you tomorrow.

**Comment by CBR09** [comment]
Hi,
Thanks for your work, I will waiting it.

**Comment by CBR09** [comment]
Any news on this?

**Comment by erikh** [comment]
This will take a bit, and we're all at dockercon this week. I'll do my best to get to it soon.

**Comment by CBR09** [comment]
Thanks you, have a good day!
