### ISSUE TITLE
vagrant reload breaks virtualbox

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#332]
This causes the disk errors we typically see when vbox is throttled. Perhaps we should solve this by checking for the file existence before both removing and creating it.

This will need changes to both Makefile and Vagrantfile

**Comment by dseevr** [comment]
I made the change so that the disks are only created/attached if they don't already exist, but I'm encounter a new problem:  the shared directories are failing to mount during `vagrant reload`

```

**Comment by dseevr** [comment]
I made the change so that the disks are only created/attached if they don't already exist, but I'm encountering a new problem:  the shared directories are failing to mount during `vagrant reload`

```
==> mon0: Configuring and enabling network interfaces...
==> mon0: Mounting shared folders...
    mon0: /tmp/bin => /home/bilrobin/src/github.com/contiv/volplugin/bin
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` tmp_bin /tmp/bin
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` tmp_bin /tmp/bin

The error output from the last command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

One thing I noticed is that the vbox drivers are not loaded.  This is what they look like on a freshly initialized environment (via `make restart`):

```
[vagrant@mon0 ~]$ lsmod | grep vbox
vboxsf                 39741  3
vboxguest             297222  2 vboxsf
vboxvideo              12658  0
drm                   349210  2 vboxvideo
```

On a reloaded environment, that command has no results.

**Comment by dseevr** [comment]
It turns out this new issue is related to the fact that part of our Ansible setup updates all the packages on the system which *may* include the kernel.  If a new kernel is installed, the vbox guest drivers are not compiled for it and will not be loaded at the next boot (i.e., the `vagrant reload` this PR is about).

**Comment by dseevr** [comment]
Manually fixing this and `vagrant reload`ing results in the guests coming up without Docker running.  This is causing etcd not to start which causes tests to fail.  Looking into this now.

**Comment by dseevr** [comment]
With #346 and #347 merged in, the new `make reload` target successfully reboots the VMs which technically completes this issue.

Many services are not set to automatically run at boot, e.g., Docker, Docker Swarm, ceph's various daemons, our daemons (netmaster, netplugin, volplugin, volsupervisor, apiserver), ucarp, and so on.

Should I open a new issue for getting what we need to start at boot?  I think we'll need @mapuri's input on this as well since it might affect the other projects/deployments.

**Comment by mapuri** [comment]
> Many services are not set to automatically run at boot, e.g., Docker, Docker Swarm, ceph's various daemons, our daemons (netmaster, netplugin, volplugin, volsupervisor, apiserver), ucarp, and so on.

oh, we discussed this over slack, we need to do `vagrant reload --provision` in `make reload` target

**Comment by dseevr** [comment]
Oh, you're right: I tried this after we discussed it but it was still failing on something (can't remember).  I just tried it now and it worked.  Thanks @mapuri

**Comment by mapuri** [comment]
kewl :+1:

**Comment by erikh** [comment]
can this issue be closed now that all changes are in master? @dseevr do you
mind doing the honors?

**Comment by dseevr** [comment]
Yup, all set now that #352 is merged.  Thanks!
