### ISSUE TITLE
Unify mountscan code in storage drivers

### ISSUE THREAD

**Issue by erikh** [contiv/volplugin#381]
This should live under `storage/mountscan` and be a merge of the mountscan code in ceph and nfs storage drivers which essentially do the same thing, just tweaked a bit.

What I would like this new code to do is parse the `/proc/self/mountinfo` text file into a structure which can then be evaluated by any storage driver for any need.

**Comment by yuva29** [comment]
@erikh https://github.com/contiv/volplugin/blob/master/storage/backend/nfs/mount.go#L38-L54 Do we need to throw these errors to the caller or can we just suppress them (ignore the specific line) and proceed processing the file further?

I would like to go with option 2; I don't want to ignore rest of the file because of the error in a line.

Let me know your thoughts.

**Comment by erikh** [comment]
hmmmmm

hmm

hmm

let us `log.Error` them and move on. I think that's the right approach.
